apiVersion: v1
kind: ServiceAccount
metadata:
  name: hydra-route-controller
  namespace: hydra-route-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hydra-route-controller-role
rules:
# Ingress permissions
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]

# Deployment permissions
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "update", "patch"]

# Service permissions
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]

# Pod permissions for metrics
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]

# Pod metrics permissions
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods", "nodes"]
  verbs: ["get", "list"]

# Event permissions for recording scaling events
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]

# ConfigMap permissions for configuration
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]

# Secret permissions for sensitive configuration
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]

# Leader election permissions
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

# Namespace permissions
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]

# Node permissions for system metrics
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hydra-route-controller-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hydra-route-controller-role
subjects:
- kind: ServiceAccount
  name: hydra-route-controller
  namespace: hydra-route-system
---
# Role for accessing metrics in ingress-nginx namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hydra-route-metrics-reader
  namespace: ingress-nginx
rules:
- apiGroups: [""]
  resources: ["services", "endpoints", "pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["services/proxy"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hydra-route-metrics-reader-binding
  namespace: ingress-nginx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hydra-route-metrics-reader
subjects:
- kind: ServiceAccount
  name: hydra-route-controller
  namespace: hydra-route-system 